services:
  kafka-gateway:
    image: node:24-bookworm-slim
    ports:
     - "3005:3005"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - /home/koli/kafka_nestjs:/home/node/app
    command: ["npm", "start"]
